---
permalink: intro-family.html 
keywords: introduction, how astra works, how Astra works, what Astra is, astra control, kubernetes, astra control service, astra control center 
summary: 'Astra, un service de gestion du cycle de vie des données applicatives Kubernetes, qui simplifie les opérations des applications avec état. Protégez, sauvegardez et migrez facilement les workloads Kubernetes, et créez instantanément des clones d"applications de travail.' 
---
= Découvrez Astra Control
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Astra Control est une solution de gestion du cycle de vie des données d'application Kubernetes qui simplifie les opérations pour les applications avec état et vous aide à stocker, protéger et déplacer vos charges de travail Kubernetes dans des environnements hybrides.



== Capacités

Astra Control offre des fonctionnalités stratégiques pour la gestion du cycle de vie des données d'application Kubernetes :

*Magasin* :

* Provisionnement de stockage dynamique pour les workloads conteneurisés
* Chiffrement à la volée des données du conteneur vers les volumes persistants
* Réplication entre régions et zones


*Protéger* :

* Détection automatisée et protection respectueuse des applications pour l'ensemble d'une application et de ses données
* Restauration instantanée d'une application à partir de n'importe quelle version de snapshot en fonction des besoins de votre organisation
* Basculement rapide dans les zones, les régions et les fournisseurs de cloud


*Déplacer* :

* Mobilité complète des applications et des données dans et entre les clusters Kubernetes et les clouds
* Des clones instantanés des applications et des données entières
* Migration des applications en un clic via une interface utilisateur Web et une API cohérentes




== Architecture

L'architecture d'Astra Control permet aux équipes IT de proposer des fonctionnalités avancées de gestion des données qui améliorent à la fois les fonctionnalités et la disponibilité des applications Kubernetes, simplifient la gestion, la protection et le déplacement des workloads conteneurisés dans les clouds publics et les environnements sur site. il offre également des fonctionnalités d'automatisation via son API REST et son SDK, qui permettent un accès par programmation pour une intégration transparente avec les workflows déjà en place.

ASTRA Control est natif de Kubernetes, ce qui permet des workflows de protection des données qui utilisent des ressources personnalisées tout en restant rétrocompatible avec l'API et le kit de développement logiciel existants. La protection native des données Kubernetes offre des avantages considérables. En s'intégrant de manière transparente avec les API et les ressources Kubernetes, la protection des données peut devenir inhérente au cycle de vie des applications, via les outils ci/CD et/ou GitOps d'une entreprise.

ASTRA Control est basé sur quatre composants complémentaires :

* *Astra Control* : Astra Control est le service de gestion centralisé pour tous les clusters gérés, fournissant des charges de travail orchestrées pour la protection et la mobilité des applications sur site ainsi que les fonctionnalités suivantes :
+
** Vue combinée de plusieurs clusters
** Protection des workflows orchestrés
** Visualisation et sélection granulaires des ressources


* *Astra Connector* : Astra Connector s'associe à Astra Control pour fournir une connexion sécurisée à chaque cluster géré, offrant ainsi une exécution locale des opérations planifiées, quel que soit l'état de la connexion, ainsi que les fonctionnalités suivantes :
+
** Exécution locale des opérations planifiées quel que soit l'état de la connexion
** Opérations locales qui distribuent et optimisent l'utilisation des ressources système d'Astra sur les clusters
** Installation locale qui active un accès avec le moins de privilèges possible au cluster pour une sécurité améliorée


* *Astra Control Provisioner* : Astra Control Provisioner fournit des fonctionnalités de provisionnement CSI de base et des capacités de gestion de stockage avancées pour une configuration de sécurité et de reprise après incident accrue, ainsi que les fonctionnalités suivantes :
+
** Provisionnement de stockage dynamique pour les workloads conteneurisés
** Gestion avancée du stockage :
+
*** Chiffrement à la volée des données du conteneur vers le volume persistant
*** Fonctionnalité SnapMirror Cloud avec réplication entre régions et zones




* *Astra Ressources personnalisées* : les ressources personnalisées utilisées sur chaque cluster offrent une approche Kubernetes native pour exécuter les opérations localement, simplifier l'intégration avec d'autres outils et l'automatisation compatibles Kubernetes, ainsi que les fonctionnalités suivantes :
+
** Intégration directe des outils de l'écosystème et automatisation des workflows
** Primitives de niveau inférieur permettant d'activer des flux de travail personnalisés






== Modèles de déploiement

Astra Control est disponible dans un modèle de déploiement unique.

*Astra Control Center* : logiciel autogéré qui assure une gestion des données compatible avec les applications de clusters Kubernetes exécutés dans votre environnement sur site. Astra Control Center peut également être installé sur plusieurs environnements de fournisseur cloud avec un système back-end de stockage NetApp Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/astra-control-center/["Documentation Astra Control Center"^]

[cols="1h,2d"]
|===
|  | Centre de contrôle Astra 


| Comment est-elle proposée ? | En tant que logiciel que vous pouvez télécharger, installer et gérer 


| Où est-il hébergé ? | Sur votre cluster Kubernetes 


| Comment est-elle mise à jour ? | Vous gérez toutes les mises à jour 


| Quelles sont les distributions Kubernetes prises en charge ?  a| 
* Azure Kubernetes Service sur Azure Stack HCI
* Anthos de Google
* Kubernetes (en amont)
* Rancher Kubernetes Engine (RKE)
* Plateforme de conteneurs Red Hat OpenShift




| Quels sont les systèmes back-end pris en charge ?  a| 
* Systèmes NetApp ONTAP AFF et FAS
* NetApp ONTAP Select
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]
* https://longhorn.io/["Longhorn"^]


|===


== Pour en savoir plus

* https://docs.netapp.com/us-en/astra-control-center/["Documentation Astra Control Center"^]
* https://docs.netapp.com/us-en/trident/index.html["Documentation Astra Trident"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["API de contrôle Astra"^]
* https://docs.netapp.com/us-en/cloudinsights/["Documentation Cloud Insights"^]
* https://docs.netapp.com/us-en/ontap/index.html["Documentation ONTAP"^]

