---
permalink: intro-family.html 
keywords: introduction, how astra works, how Astra works, what Astra is, astra control, kubernetes, astra control service, astra control center 
summary: 'Astra, un service de gestion du cycle de vie des données applicatives Kubernetes, qui simplifie les opérations des applications avec état. Protégez, sauvegardez et migrez facilement les workloads Kubernetes, et créez instantanément des clones d"applications de travail.' 
---
= Découvrez la gamme de produits Astra
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La gamme NetApp Astra fournit des fonctionnalités de gestion des données d'application et de stockage pour les applications cloud.

Les offres d'Astra sont notamment :

* *Astra Control* : utilisez des outils de gestion des données intégrant la cohérence applicative qui gèrent, protègent et déplacent les workloads Kubernetes dans les clouds publics et sur site.​
+
** *Astra Control Service* : utilisez un service géré par NetApp pour la gestion des données des workloads Kubernetes dans les clouds publics.
** *Astra Control Center* : utilisez un logiciel autogéré pour gérer les données des workloads Kubernetes sur site.


* *Astra Trident* : utilisez le provisionnement et la gestion du stockage conformes à la norme CSI (Container Storage interface) pour les workloads Kubernetes avec les fournisseurs de stockage NetApp.




== Contrôle Astra

Astra Control est une solution de gestion du cycle de vie des données applicatives Kubernetes qui simplifie les opérations des applications avec état. Protégez, sauvegardez et migrez facilement les workloads Kubernetes, et créez instantanément des clones d'applications de travail.



=== Caractéristiques

Astra Control offre des fonctionnalités stratégiques pour la gestion du cycle de vie des données d'application Kubernetes :

* Gérez automatiquement le stockage persistant
* Création de copies Snapshot et de sauvegardes à la demande intégrant la cohérence applicative
* Automatisation des opérations de sauvegarde et de snapshots basées sur des règles
* Migrez des applications et des données d'un cluster Kubernetes vers un autre
* Réplication d'applications sur un système distant à l'aide de la technologie NetApp SnapMirror (Astra Control Center)
* Clonage d'applications de la phase de transfert à la production
* Visualiser l'état de santé et de protection des applications
* Implémentation de vos workflows de sauvegarde et de migration à l'aide d'une interface utilisateur web ou d'une API




=== Modèles de déploiement

Astra Control est disponible dans deux modèles de déploiement :

* *Astra Control Service* : service géré par NetApp qui offre une gestion des données compatible avec les applications des clusters Kubernetes dans des environnements de plusieurs fournisseurs cloud ainsi que des clusters Kubernetes autogérés.
+
https://docs.netapp.com/us-en/astra/index.html["Documentation relative au service après-vente Astra Control"^]

* *Astra Control Center* : logiciel autogéré qui assure une gestion des données compatible avec les applications de clusters Kubernetes exécutés dans votre environnement sur site. Astra Control Center peut également être installé sur plusieurs environnements de fournisseur cloud avec un système back-end de stockage NetApp Cloud Volumes ONTAP.
+
https://docs.netapp.com/us-en/astra-control-center/["Documentation Astra Control Center"^]



[cols="1h,2a,2a"]
|===
|  | Service Astra Control | Centre de contrôle Astra 


| Comment est-elle proposée ?  a| 
En tant que service cloud entièrement géré de NetApp
 a| 
En tant que logiciel que vous téléchargez, installez et gérez



| Où est-il hébergé ?  a| 
Dans le cloud public de votre choix
 a| 
Sur votre cluster Kubernetes



| Comment est-elle mise à jour ?  a| 
Géré par NetApp
 a| 
Vous gérez toutes les mises à jour



| Qu'est-ce que le système back-end prend en charge ?  a| 
* Amazon Web Services :
+
** Amazon EBS
** Amazon FSX pour NetApp ONTAP
** link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html["Cloud Volumes ONTAP"^]


* Google Cloud :
+
** Disque persistant Google
** NetApp Cloud Volumes Service
** link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["Cloud Volumes ONTAP"^]


* Microsoft Azure :
+
** Disques gérés Azure
** Azure NetApp Files
** link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html["Cloud Volumes ONTAP"^]


* Clusters autogérés :
+
** Amazon EBS
** Disque persistant Google
** Disques gérés Azure
** link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-overview-cvo.html["Cloud Volumes ONTAP"^]



 a| 
* Systèmes NetApp ONTAP AFF et FAS
* link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-overview-cvo.html["Cloud Volumes ONTAP"^]


|===


== Astra Trident

Astra Trident est une mise en œuvre open source de NetApp qui consiste dans un conteneur Kubernetes Storage interface (CSI) driver​. Astra Trident assure l'orchestration et la connectivité des données pour Kubernetes applications​.

https://docs.netapp.com/us-en/trident/index.html["Documentation Astra Trident"^]



== Pour en savoir plus

* https://docs.netapp.com/us-en/astra/index.html["Documentation relative au service après-vente Astra Control"^]
* https://docs.netapp.com/us-en/astra-control-center/["Documentation Astra Control Center"^]
* https://docs.netapp.com/us-en/trident/index.html["Documentation Astra Trident"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["API de contrôle Astra"^]
* https://docs.netapp.com/us-en/cloudinsights/["Documentation Cloud Insights"^]
* https://docs.netapp.com/us-en/ontap/index.html["Documentation ONTAP"^]

